import { StyleSheet } from 'react-native';
import COLORS from '../../utils/colors';
const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: COLORS.GRAY_LIGHT },
  container: { padding: 12 },
  topGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  topCell: {
    flex: 1,
    marginHorizontal: 4,
    backgroundColor: COLORS.WHITE,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.1)',
    color: COLORS.BLACK,
    minHeight: 44,
  },
  // Radio Group Row Style
  radioGroupRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginHorizontal: 0,
    paddingHorizontal: 4,
  },
  radioColumnOption: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 2,
    paddingVertical: 4,
    borderRadius: 6,
    marginHorizontal: 2,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  radioGroupRate: { flex: 2 },
  radioGroupService: { flex: 1.5 },
  radioColumnOptionActive: {
    backgroundColor: COLORS.PRIMARY,
    borderColor: COLORS.PRIMARY_DARK,
  },
  radioColumnText: {
    marginTop: 2,
    fontSize: 10,
    color: COLORS.PRIMARY_DARK,
    fontWeight: '600',
    textAlign: 'center',
  },
  radioColumnTextActive: {
    marginTop: 2,
    fontSize: 10,
    color: COLORS.WHITE,
    fontWeight: '700',
    textAlign: 'center',
  },

  perHeadInfoInput: {
    minHeight: 40,
    backgroundColor: '#f9f9f9',
    borderRadius: 6,
    padding: 10,
    textAlignVertical: 'top',
    borderWidth: 1,
    borderColor: '#eee',
    color: COLORS.BLACK,
    marginTop: 8,
  },
  perHeadExpanded: { minHeight: 100 },
  section: {
    backgroundColor: COLORS.WHITE,
    borderRadius: 8,
    padding: 8,
    marginBottom: 12,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    fontWeight: '700',
    color: COLORS.PRIMARY_DARK,
    marginBottom: 6,
    paddingHorizontal: 4,
  },
  headerRow: {
    flexDirection: 'row',
    backgroundColor: COLORS.PRIMARY_DARK,
    borderRadius: 4,
    overflow: 'hidden',
  },
  headerCell: {
    color: COLORS.WHITE,
    textAlign: 'center',
    paddingVertical: 8,
    borderRightWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    fontWeight: '700',
    fontSize: 12,
  },
  row: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#ccc',
    borderTopWidth: 0,
  },
  cell: {
    justifyContent: 'center',
    alignItems: 'center',
    borderRightWidth: 1,
    borderColor: '#ccc',
    minHeight: 40,
    paddingHorizontal: 2,
  },
  cellText: { textAlign: 'center', color: COLORS.BLACK, fontSize: 12 },
  cellInput: {
    flex: 1,
    textAlign: 'center',
    color: COLORS.BLACK,
    width: '100%',
    paddingVertical: 6,
    fontSize: 12,
  },
  addAndTotalsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    justifyContent: 'space-between',
  },
  smallAddLeft: {
    backgroundColor: COLORS.PRIMARY,
    padding: 8,
    borderRadius: 6,
    marginRight: 8,
  },
  ownerAmountWrap: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'flex-start',
    marginRight: 12,
  },
  ownerInput: {
    minWidth: 120,
    borderWidth: 1,
    borderColor: '#eee',
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: '#fafafa',
  },

  beverageRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    gap: 12,
  },
  checkboxOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#eee',
    marginRight: 12,
    backgroundColor: '#fff',
  },
  checkboxOptionActive: {
    backgroundColor: '#f5f5f5',
    borderColor: COLORS.PRIMARY,
  },
  checkboxLabel: {
    marginLeft: 8,
    fontWeight: '600',
    color: COLORS.PRIMARY_DARK,
  },

  beverageTotalRow: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },

  summaryBox: { alignItems: 'flex-end', paddingHorizontal: 8 },
  summaryLabel: { color: COLORS.GRAY_DARK, fontSize: 12 },
  summaryValue: { fontWeight: '800', fontSize: 16, color: COLORS.ACCENT },

  grandTotalRow: {
    padding: 12,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
    marginBottom: 12,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#eee',
  },
  grandLabel: { color: COLORS.PRIMARY_DARK, fontSize: 18, fontWeight: '700' },
  grandValue: { color: COLORS.PRIMARY_DARK, fontSize: 18, fontWeight: '700' },

  advanceRow: { flexDirection: 'row', gap: 12, marginTop: 8 },
  advanceOption: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#eee',
    backgroundColor: '#fff',
  },
  advanceOptionActive: {
    backgroundColor: '#f0f0f0',
    borderColor: COLORS.PRIMARY,
  },
  advanceText: { color: COLORS.PRIMARY_DARK, fontWeight: '700' },
  advanceTextActive: { color: COLORS.PRIMARY_DARK, fontWeight: '800' },
  advanceInputRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  advanceInput: {
    minWidth: 120,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#eee',
    borderRadius: 6,
    backgroundColor: '#fafafa',
    textAlign: 'right',
  },
  bankPickerWrap: {
    minWidth: 160,
    borderWidth: 1,
    borderColor: '#eee',
    borderRadius: 6,
    overflow: 'hidden',
    backgroundColor: '#fff',
  },
  // NEW: Bank display row
  bankDisplayRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
    padding: 8,
    backgroundColor: COLORS.PRIMARY,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: COLORS.PRIMARY_DARK,
  },
  bankNameText: {
    fontWeight: '700',
    color: COLORS.WHITE,
    fontSize: 14,
  },

  // NEW: Button row for side-by-side buttons
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 10,
  },
  saveBtn: {
    width: '100%',
    backgroundColor: COLORS.PRIMARY_DARK,
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
  },
  saveBtnText: { color: COLORS.ACCENT, fontWeight: '800', fontSize: 16 },
  downloadBtn: {
    flex: 1,
    backgroundColor: COLORS.PRIMARY,
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
  },
  downloadBtnText: { color: COLORS.WHITE, fontWeight: '800', fontSize: 16 },

  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCard: {
    width: '90%',
    backgroundColor: COLORS.WHITE,
    borderRadius: 8,
    padding: 12,
  },
  modalTitle: {
    fontWeight: '700',
    marginBottom: 8,
    color: COLORS.PRIMARY_DARK,
  },
  modalClose: { marginTop: 8, alignItems: 'flex-end' },
  totalLabel: { fontWeight: '700', color: COLORS.PRIMARY_DARK, fontSize: 14 },
  modeNoteText: {
    textAlign: 'center',
    color: COLORS.GRAY_DARK,
    marginTop: 8,
    fontStyle: 'italic',
  },
  infoCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingVertical: 10,
    marginBottom: 14,
  },
  inputRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  input: {
    flex: 1,
    borderBottomWidth: 1,
    borderColor: '#ccc',
    marginHorizontal: 4,
    fontSize: 14,
    color: COLORS.DARK,
  },
  editingCell: {
    borderColor: COLORS.ACCENT,
    borderWidth: 2,
    backgroundColor: COLORS.WHITE,
  },
  discountRow: {
    marginTop: 8,
  },
  discountTypeRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 12,
  },
  discountTypeOption: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: COLORS.PRIMARY,
    backgroundColor: COLORS.WHITE,
  },
  discountTypeOptionActive: {
    backgroundColor: COLORS.PRIMARY,
  },
  discountTypeText: {
    color: COLORS.PRIMARY,
    fontWeight: '600',
  },
  discountTypeTextActive: {
    color: COLORS.WHITE,
    fontWeight: '700',
  },
  discountInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  discountInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#ddd',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
    backgroundColor: '#fafafa',
    marginRight: 12,
    marginLeft: 6,
    textAlign: 'center',
    fontWeight: '600',
  },
  discountValueText: {
    fontWeight: '700',
    color: COLORS.PRIMARY_DARK,
    fontSize: 14,
  },

  // Sub Total Row
  subTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 12,
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#e9ecef',
  },
  subTotalLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.PRIMARY_DARK,
  },
  subTotalValue: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.PRIMARY_DARK,
  },

  // Table Body
  tableBody: {
    height: 'auto',
  },

  // Add and Totals Row
  addAndTotalsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    justifyContent: 'space-between',
  },
  smallAddLeft: {
    backgroundColor: COLORS.PRIMARY,
    padding: 10,
    borderRadius: 6,
    marginRight: 8,
  },
  ownerAmountWrap: {
    flex: 0.7,
    marginRight: 12,
  },
  ownerInput: {
    borderWidth: 1,
    borderColor: '#ddd',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
    backgroundColor: '#fafafa',
    textAlign: 'center',
    fontWeight: '600',
  },
  ownerInputFocused: {
    borderColor: COLORS.ACCENT,
    borderWidth: 2,
    backgroundColor: COLORS.WHITE,
  },
  totalInlineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    justifyContent: 'flex-end',
  },
  totalLabelSmall: {
    fontWeight: '600',
    color: COLORS.PRIMARY_DARK,
    fontSize: 13,
    marginRight: 8,
  },
  totalCellSmall: {
    minWidth: 80,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
    backgroundColor: '#e9ecef',
    justifyContent: 'center',
    alignItems: 'center',
  },
  totalValueSmall: {
    fontWeight: '700',
    color: COLORS.PRIMARY_DARK,
    fontSize: 14,
  },

  // Number formatting for all amount displays
  amountText: {
    fontWeight: '600',
    color: COLORS.PRIMARY_DARK,
  },
});
export default styles;
